AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS Budget with a threshold of $0 to catch any charges

Parameters:
  Email:
    Type: String
    Description: Email address to be subscribed to the SNS topic

Resources:
  ZeroBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: ZeroBudgetAlert
        BudgetLimit:
          Amount: 1
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        FilterExpression:
          Not:
            Dimensions:
              Key: RECORD_TYPE
              Values:
                - Credit
                - Refund
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 0.01
            ThresholdType: ABSOLUTE_VALUE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email