AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Read-only User Restricted to Specific IP (localhost backup)

Parameters:
  AllowedIP:
    Type: String
    Default: 203.0.113.25/32
    Description: IP allowed to access the S3 bucket

Resources:
  ReadOnlyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-readonly-bucket

  ReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: readonly-user

  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3ReadOnlyPolicy
      Users:
        - !Ref ReadOnlyUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${ReadOnlyBucket}/*

  ReadOnlyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReadOnlyBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyNotFromIP
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${ReadOnlyBucket}
              - !Sub arn:aws:s3:::${ReadOnlyBucket}/*
            Condition:
              NotIpAddress:
                aws:SourceIp: !Ref AllowedIP

  ReadOnlyUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ReadOnlyUser

Outputs:
  BucketName:
    Value: !Ref ReadOnlyBucket
  IAMUser:
    Value: !Ref ReadOnlyUser
  AccessKeyId:
    Value: !Ref ReadOnlyUserAccessKey
  SecretAccessKey:
    Value: !GetAtt ReadOnlyUserAccessKey.SecretAccessKey